/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PluginHelperPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/PluginCatalogModal.ts
var import_obsidian = require("obsidian");

// src/community.ts
var COMMUNITY_URL = "https://raw.githubusercontent.com/obsidianmd/obsidian-releases/master/community-plugins.json";
var CACHE_MS = 24 * 60 * 60 * 1e3;
var memoryCache = null;
var memoryCacheTime = 0;
async function fetchCommunityPlugins(force = false) {
  const now = Date.now();
  if (!force && memoryCache && now - memoryCacheTime < CACHE_MS) {
    return memoryCache;
  }
  const res = await fetch(COMMUNITY_URL);
  if (!res.ok) {
    throw new Error(`\u62C9\u53D6\u793E\u533A\u63D2\u4EF6\u5217\u8868\u5931\u8D25 (${res.status})`);
  }
  const list = await res.json();
  const map = /* @__PURE__ */ new Map();
  for (const item of list) {
    map.set(item.id, item);
  }
  memoryCache = map;
  memoryCacheTime = now;
  return map;
}
function getOfficialDescription(community, pluginId) {
  var _a, _b;
  return (_b = (_a = community.get(pluginId)) == null ? void 0 : _a.description) != null ? _b : "";
}

// src/translate.ts
async function translateEnToZh(text) {
  const trimmed = text.trim();
  if (!trimmed) return "";
  const url = "https://translate.googleapis.com/translate_a/single?" + new URLSearchParams({
    client: "gtx",
    sl: "en",
    tl: "zh-CN",
    dt: "t",
    q: trimmed
  });
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`\u7FFB\u8BD1\u8BF7\u6C42\u5931\u8D25 (${res.status})`);
  }
  const data = await res.json();
  if (!Array.isArray(data[0])) return trimmed;
  return data[0].map((chunk) => chunk[0]).join("").trim();
}

// src/plugin-data.ts
async function buildPluginRows(plugin) {
  var _a, _b;
  const app = plugin.app;
  const community = await fetchCommunityPlugins().catch(() => /* @__PURE__ */ new Map());
  const manifests = app.plugins.manifests;
  const enabledIds = app.plugins.enabledPlugins;
  const rows = [];
  for (const id of Object.keys(manifests)) {
    if (id === plugin.manifest.id) continue;
    const manifest = manifests[id];
    const entry = ensureEntry(plugin.settings, id);
    const official = getOfficialDescription(community, id) || entry.officialDesc || manifest.description || "";
    if (official) {
      entry.officialDesc = official;
    }
    rows.push({
      id,
      manifestName: manifest.name,
      version: manifest.version,
      enabled: enabledIds.has(id),
      officialDesc: official,
      annotationDesc: (_b = (_a = entry.autoTranslatedDesc) == null ? void 0 : _a.trim()) != null ? _b : "",
      myDesc: resolveMyDesc(entry),
      isDescCustomized: !!entry.descCustomized
    });
  }
  rows.sort(
    (a, b) => a.manifestName.localeCompare(b.manifestName, "zh-CN")
  );
  await plugin.saveSettings();
  return rows;
}
function resolveMyDesc(entry) {
  var _a, _b;
  if (entry.descCustomized && ((_a = entry.customDesc) == null ? void 0 : _a.trim())) {
    return entry.customDesc.trim();
  }
  if ((_b = entry.autoTranslatedDesc) == null ? void 0 : _b.trim()) {
    return entry.autoTranslatedDesc.trim();
  }
  return "";
}
function ensureEntry(settings, pluginId) {
  if (!settings.entries[pluginId]) {
    settings.entries[pluginId] = {};
  }
  return settings.entries[pluginId];
}
async function syncDescriptions(plugin, onProgress) {
  var _a;
  const community = await fetchCommunityPlugins(true).catch(() => /* @__PURE__ */ new Map());
  const manifests = plugin.app.plugins.manifests;
  let translated = 0;
  plugin.settings.communityFetchedAt = Date.now();
  for (const id of Object.keys(manifests)) {
    if (id === plugin.manifest.id) continue;
    const entry = ensureEntry(plugin.settings, id);
    const official = getOfficialDescription(community, id) || manifests[id].description || "";
    if (!official) continue;
    const officialChanged = entry.officialDesc !== official;
    entry.officialDesc = official;
    if (entry.descCustomized) continue;
    const needsTranslate = !((_a = entry.autoTranslatedDesc) == null ? void 0 : _a.trim()) || officialChanged;
    if (!needsTranslate) continue;
    onProgress == null ? void 0 : onProgress(`\u6B63\u5728\u7FFB\u8BD1\uFF1A${manifests[id].name}\u2026`);
    try {
      entry.autoTranslatedDesc = await translateEnToZh(official);
      translated++;
      await sleep(300);
    } catch (e) {
    }
  }
  await plugin.saveSettings();
  return translated;
}
function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
function openPluginSettings(app, pluginId) {
  const setting = app.setting;
  if (!setting) return;
  setting.open();
  setTimeout(() => {
    if (typeof setting.openTabById === "function") {
      setting.openTabById(pluginId);
    }
  }, 50);
}

// src/render-plugin-card.ts
function renderOfficialWithAnnotation(container, official, annotation) {
  container.empty();
  if (!official) {
    container.setText("\uFF08\u6682\u65E0\u5B98\u65B9\u8BF4\u660E\uFF09");
    return;
  }
  container.createSpan({
    cls: "plugin-helper-official-original",
    text: official
  });
  if (annotation) {
    container.createSpan({
      cls: "plugin-helper-official-annotation",
      text: `\uFF08\u6CE8\u91CA\uFF1A${annotation}\uFF09`
    });
  }
}
function renderPluginCard(parent, row, plugin, options = {}) {
  var _a;
  const variant = (_a = options.variant) != null ? _a : "sidebar";
  if (variant === "modal") {
    renderModalCard(parent, row, options);
  } else {
    renderSidebarCard(parent, row, plugin, options);
  }
}
function renderModalCard(parent, row, options) {
  const card = parent.createDiv({
    cls: "plugin-helper-card plugin-helper-card-modal"
  });
  const top = card.createDiv({ cls: "plugin-helper-card-top" });
  const topLeft = top.createDiv({ cls: "plugin-helper-card-top-left" });
  topLeft.createEl("span", {
    cls: "plugin-helper-card-name",
    text: row.manifestName
  });
  topLeft.createSpan({
    cls: row.enabled ? "plugin-helper-badge plugin-helper-badge-on" : "plugin-helper-badge plugin-helper-badge-off",
    text: row.enabled ? "\u5DF2\u542F\u7528" : "\u672A\u542F\u7528"
  });
  const settingsBtn = top.createEl("button", {
    cls: "plugin-helper-settings-corner",
    text: "\u6253\u5F00\u8BBE\u7F6E"
  });
  settingsBtn.addEventListener("click", () => {
    var _a;
    (_a = options.onOpenSettings) == null ? void 0 : _a.call(options, row.id);
  });
  card.createDiv({
    cls: "plugin-helper-card-meta",
    text: `v${row.version} \xB7 ${row.id}`
  });
  const officialBlock = card.createDiv({ cls: "plugin-helper-desc-block" });
  officialBlock.createDiv({
    cls: "plugin-helper-desc-label",
    text: "\u5B98\u65B9\u8BF4\u660E"
  });
  const officialEl = officialBlock.createDiv({ cls: "plugin-helper-desc-official" });
  renderOfficialWithAnnotation(officialEl, row.officialDesc, row.annotationDesc);
}
function renderSidebarCard(parent, row, plugin, options) {
  var _a;
  const card = parent.createDiv({ cls: "plugin-helper-card" });
  const top = card.createDiv({ cls: "plugin-helper-card-top" });
  const topLeft = top.createDiv({ cls: "plugin-helper-card-top-left" });
  topLeft.createEl("span", {
    cls: "plugin-helper-card-name",
    text: row.manifestName
  });
  topLeft.createSpan({
    cls: row.enabled ? "plugin-helper-badge plugin-helper-badge-on" : "plugin-helper-badge plugin-helper-badge-off",
    text: row.enabled ? "\u5DF2\u542F\u7528" : "\u672A\u542F\u7528"
  });
  card.createDiv({
    cls: "plugin-helper-card-meta",
    text: `v${row.version} \xB7 ${row.id}`
  });
  const officialBlock = card.createDiv({ cls: "plugin-helper-desc-block" });
  officialBlock.createDiv({
    cls: "plugin-helper-desc-label",
    text: "\u5B98\u65B9\u8BF4\u660E"
  });
  const officialEl = officialBlock.createDiv({ cls: "plugin-helper-desc-official" });
  renderOfficialWithAnnotation(officialEl, row.officialDesc, row.annotationDesc);
  const myBlock = card.createDiv({ cls: "plugin-helper-desc-block" });
  myBlock.createDiv({
    cls: "plugin-helper-desc-label",
    text: "\u6211\u7684\u8BF4\u660E"
  });
  myBlock.createDiv({
    cls: "plugin-helper-desc-hint",
    text: "\u9ED8\u8BA4\u4E3A\u81EA\u52A8\u7FFB\u8BD1\uFF0C\u53EF\u81EA\u884C\u4FEE\u6539\uFF1B\u4FEE\u6539\u4E0D\u4F1A\u5F71\u54CD\u4E0A\u65B9\u5B98\u65B9\u539F\u6587\u4E0E\u6CE8\u91CA\u3002"
  });
  const descInput = myBlock.createEl("textarea", {
    placeholder: "\u7559\u7A7A\u5219\u4F7F\u7528\u81EA\u52A8\u7FFB\u8BD1\uFF1B\u70B9\u51FB\u300C\u5237\u65B0\u7FFB\u8BD1\u300D\u53EF\u91CD\u65B0\u751F\u6210",
    cls: "plugin-helper-textarea"
  });
  descInput.value = resolveMyDesc((_a = plugin.settings.entries[row.id]) != null ? _a : {});
  let saveTimer = null;
  const scheduleSave = () => {
    if (saveTimer) window.clearTimeout(saveTimer);
    saveTimer = window.setTimeout(() => void saveMyDesc(), 500);
  };
  const saveMyDesc = async () => {
    var _a2, _b, _c;
    const e = ensureEntry(plugin.settings, row.id);
    const newDesc = descInput.value.trim();
    const autoDesc = (_b = (_a2 = e.autoTranslatedDesc) == null ? void 0 : _a2.trim()) != null ? _b : "";
    if (!newDesc) {
      e.customDesc = void 0;
      e.descCustomized = false;
    } else if (newDesc === autoDesc) {
      e.customDesc = void 0;
      e.descCustomized = false;
    } else {
      e.customDesc = newDesc;
      e.descCustomized = true;
    }
    await plugin.saveSettings();
    row.myDesc = resolveMyDesc(e);
    row.isDescCustomized = !!e.descCustomized;
    updateResetButton();
    (_c = options.onSaved) == null ? void 0 : _c.call(options);
  };
  descInput.addEventListener("input", scheduleSave);
  const btnRow = card.createDiv({ cls: "plugin-helper-card-btns" });
  let resetBtn = null;
  const settingsBtn = btnRow.createEl("button", { text: "\u6253\u5F00\u63D2\u4EF6\u8BBE\u7F6E" });
  settingsBtn.addEventListener("click", () => {
    var _a2;
    (_a2 = options.onOpenSettings) == null ? void 0 : _a2.call(options, row.id);
  });
  const updateResetButton = () => {
    const e = plugin.settings.entries[row.id];
    const show = !!(e == null ? void 0 : e.descCustomized);
    if (show && !resetBtn) {
      resetBtn = btnRow.createEl("button", {
        text: "\u6062\u590D\u81EA\u52A8\u7FFB\u8BD1",
        cls: "mod-warning"
      });
      resetBtn.addEventListener("click", async () => {
        var _a2, _b;
        const entry = ensureEntry(plugin.settings, row.id);
        entry.customDesc = void 0;
        entry.descCustomized = false;
        descInput.value = (_a2 = entry.autoTranslatedDesc) != null ? _a2 : "";
        await plugin.saveSettings();
        row.myDesc = resolveMyDesc(entry);
        row.isDescCustomized = false;
        resetBtn == null ? void 0 : resetBtn.remove();
        resetBtn = null;
        (_b = options.onSaved) == null ? void 0 : _b.call(options);
      });
    } else if (!show && resetBtn) {
      resetBtn.remove();
      resetBtn = null;
    }
  };
  updateResetButton();
  card.dataset.pluginId = row.id;
  card.syncFromRow = (updated) => {
    renderOfficialWithAnnotation(
      officialEl,
      updated.officialDesc,
      updated.annotationDesc
    );
    if (document.activeElement !== descInput) {
      const entry = plugin.settings.entries[row.id];
      descInput.value = resolveMyDesc(entry != null ? entry : {});
    }
    Object.assign(row, updated);
    updateResetButton();
  };
}
function filterPluginRows(rows, query) {
  const q = query.trim().toLowerCase();
  if (!q) return rows;
  return rows.filter(
    (r) => r.manifestName.toLowerCase().includes(q) || r.officialDesc.toLowerCase().includes(q) || r.annotationDesc.toLowerCase().includes(q) || r.myDesc.toLowerCase().includes(q) || r.id.toLowerCase().includes(q)
  );
}

// src/PluginCatalogModal.ts
var PluginCatalogModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.rows = [];
    this.filter = "";
    this.listEl = null;
    this.statusEl = null;
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl, modalEl } = this;
    contentEl.empty();
    modalEl.addClass("plugin-helper-modal");
    contentEl.addClass("plugin-helper-catalog", "plugin-helper-modal-content");
    contentEl.createEl("h2", { text: "\u63D2\u4EF6\u8BF4\u660E\u4E66" });
    contentEl.createEl("p", {
      cls: "plugin-helper-modal-hint",
      text: "\u53EA\u8BFB\u67E5\u9605\uFF1A\u5B98\u65B9\u539F\u6587 + \u4E2D\u6587\u6CE8\u91CA\u3002\u7F16\u8F91\u300C\u6211\u7684\u8BF4\u660E\u300D\u8BF7\u4F7F\u7528\u4FA7\u8FB9\u680F\u3002"
    });
    const toolbar = contentEl.createDiv({ cls: "plugin-helper-modal-toolbar" });
    const searchInput = toolbar.createEl("input", {
      type: "search",
      placeholder: "\u641C\u7D22\u63D2\u4EF6\u540D\u6216\u8BF4\u660E\u2026",
      cls: "plugin-helper-search"
    });
    const refreshBtn = toolbar.createEl("button", { text: "\u5237\u65B0\u7FFB\u8BD1" });
    this.statusEl = toolbar.createDiv({ cls: "plugin-helper-status" });
    this.listEl = contentEl.createDiv({ cls: "plugin-helper-list" });
    searchInput.addEventListener("input", () => {
      this.filter = searchInput.value;
      this.renderList();
    });
    refreshBtn.addEventListener("click", () => void this.handleRefresh(refreshBtn));
    void this.loadRows();
  }
  onClose() {
    this.listEl = null;
    this.statusEl = null;
    this.contentEl.empty();
  }
  async loadRows() {
    if (this.statusEl) this.statusEl.setText("\u52A0\u8F7D\u4E2D\u2026");
    try {
      this.rows = await buildPluginRows(this.plugin);
      if (this.statusEl) {
        this.statusEl.setText(`\u5171 ${this.rows.length} \u4E2A\u63D2\u4EF6`);
      }
      this.renderList();
    } catch (e) {
      if (this.statusEl) this.statusEl.setText("\u52A0\u8F7D\u5931\u8D25");
      new import_obsidian.Notice(String(e));
    }
  }
  async handleRefresh(refreshBtn) {
    refreshBtn.disabled = true;
    if (this.statusEl) this.statusEl.setText("\u7FFB\u8BD1\u4E2D\u2026");
    try {
      const n = await syncDescriptions(this.plugin, (m) => {
        if (this.statusEl) this.statusEl.setText(m);
      });
      this.rows = await buildPluginRows(this.plugin);
      if (this.statusEl) this.statusEl.setText(`\u5B8C\u6210\uFF0C\u66F4\u65B0\u4E86 ${n} \u6761`);
      this.renderList();
      new import_obsidian.Notice(`\u5DF2\u66F4\u65B0 ${n} \u6761\u7FFB\u8BD1`);
    } catch (e) {
      if (this.statusEl) this.statusEl.setText("\u5931\u8D25");
      new import_obsidian.Notice(String(e));
    } finally {
      refreshBtn.disabled = false;
    }
  }
  renderList() {
    if (!this.listEl) return;
    this.listEl.empty();
    const filtered = filterPluginRows(this.rows, this.filter);
    if (filtered.length === 0) {
      this.listEl.createDiv({
        cls: "plugin-helper-empty",
        text: this.filter ? "\u6CA1\u6709\u5339\u914D\u7684\u63D2\u4EF6" : "\u672A\u68C0\u6D4B\u5230\u7B2C\u4E09\u65B9\u63D2\u4EF6"
      });
      return;
    }
    for (const row of filtered) {
      renderPluginCard(this.listEl, row, this.plugin, {
        variant: "modal",
        onOpenSettings: (id) => {
          this.close();
          openPluginSettings(this.app, id);
        }
      });
    }
  }
};

// src/PluginCatalogView.ts
var import_obsidian2 = require("obsidian");
var VIEW_TYPE_PLUGIN_CATALOG = "plugin-helper-catalog";
var PluginCatalogView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.rows = [];
    this.filter = "";
    this.listEl = null;
    this.statusEl = null;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_PLUGIN_CATALOG;
  }
  getDisplayText() {
    return "\u63D2\u4EF6\u8BF4\u660E\u4E66";
  }
  getIcon() {
    return "book-open";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("plugin-helper-catalog");
    const header = container.createDiv({ cls: "plugin-helper-header" });
    const titleRow = header.createDiv({ cls: "plugin-helper-title-row" });
    titleRow.createEl("h4", { text: "\u63D2\u4EF6\u8BF4\u660E\u4E66" });
    const actions = titleRow.createDiv({ cls: "plugin-helper-actions" });
    const refreshBtn = actions.createEl("button", {
      cls: "clickable-icon",
      attr: { "aria-label": "\u5237\u65B0\u5E76\u7FFB\u8BD1\u8BF4\u660E" }
    });
    (0, import_obsidian2.setIcon)(refreshBtn, "refresh-cw");
    refreshBtn.addEventListener("click", () => void this.handleRefresh());
    header.createDiv({
      cls: "plugin-helper-panel-hint",
      text: "\u5B98\u65B9\u8BF4\u660E\u4E3A\u539F\u6587\u5E76\u9644\u4E2D\u6587\u6CE8\u91CA\uFF08\u53EA\u8BFB\uFF09\uFF1B\u4E0B\u65B9\u300C\u6211\u7684\u8BF4\u660E\u300D\u53EF\u7F16\u8F91\uFF0C\u4FEE\u6539\u4E0D\u5F71\u54CD\u5B98\u65B9\u6570\u636E\u3002"
    });
    const searchWrap = header.createDiv({ cls: "plugin-helper-search-wrap" });
    const searchInput = searchWrap.createEl("input", {
      type: "search",
      placeholder: "\u641C\u7D22\u63D2\u4EF6\u540D\u6216\u8BF4\u660E\u2026",
      cls: "plugin-helper-search"
    });
    searchInput.addEventListener("input", () => {
      this.filter = searchInput.value;
      this.renderList();
    });
    this.statusEl = header.createDiv({ cls: "plugin-helper-status" });
    this.listEl = container.createDiv({ cls: "plugin-helper-list" });
    await this.loadRows();
  }
  async onClose() {
    this.listEl = null;
    this.statusEl = null;
  }
  setStatus(text) {
    if (this.statusEl) this.statusEl.setText(text);
  }
  async loadRows() {
    this.setStatus("\u52A0\u8F7D\u4E2D\u2026");
    try {
      this.rows = await buildPluginRows(this.plugin);
      this.setStatus(`\u5171 ${this.rows.length} \u4E2A\u7B2C\u4E09\u65B9\u63D2\u4EF6`);
      this.renderList();
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      this.setStatus(`\u52A0\u8F7D\u5931\u8D25\uFF1A${msg}`);
    }
  }
  async handleRefresh() {
    this.setStatus("\u6B63\u5728\u62C9\u53D6\u5B98\u65B9\u8BF4\u660E\u5E76\u7FFB\u8BD1\u2026");
    try {
      const count = await syncDescriptions(
        this.plugin,
        (msg) => this.setStatus(msg)
      );
      this.rows = await buildPluginRows(this.plugin);
      this.setStatus(
        count > 0 ? `\u5DF2\u7FFB\u8BD1 ${count} \u6761\u8BF4\u660E\uFF0C\u5171 ${this.rows.length} \u4E2A\u63D2\u4EF6` : `\u8BF4\u660E\u5DF2\u662F\u6700\u65B0\uFF0C\u5171 ${this.rows.length} \u4E2A\u63D2\u4EF6`
      );
      this.renderList();
      new import_obsidian2.Notice(`\u63D2\u4EF6\u8BF4\u660E\u4E66\uFF1A\u5DF2\u66F4\u65B0 ${count} \u6761\u7FFB\u8BD1`);
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      this.setStatus(`\u5237\u65B0\u5931\u8D25\uFF1A${msg}`);
      new import_obsidian2.Notice(`\u5237\u65B0\u5931\u8D25\uFF1A${msg}`);
    }
  }
  renderList() {
    if (!this.listEl) return;
    this.listEl.empty();
    const filtered = filterPluginRows(this.rows, this.filter);
    if (filtered.length === 0) {
      this.listEl.createDiv({
        cls: "plugin-helper-empty",
        text: this.filter ? "\u6CA1\u6709\u5339\u914D\u7684\u63D2\u4EF6" : "\u672A\u68C0\u6D4B\u5230\u7B2C\u4E09\u65B9\u63D2\u4EF6"
      });
      return;
    }
    for (const row of filtered) {
      renderPluginCard(this.listEl, row, this.plugin, {
        variant: "sidebar",
        onOpenSettings: (id) => openPluginSettings(this.app, id)
      });
    }
  }
};

// src/settings-tab.ts
var import_obsidian3 = require("obsidian");
var PluginHelperSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian3.Setting(containerEl).setName("\u63D2\u4EF6\u8BF4\u660E\u4E66").setHeading();
    new import_obsidian3.Setting(containerEl).setName("\u6253\u5F00\u63D2\u4EF6\u4E00\u89C8\uFF08\u4FA7\u8FB9\u680F\uFF09").setDesc("\u5728\u5DE6\u4FA7\u680F\u6253\u5F00\u5E38\u9A7B\u9762\u677F\uFF0C\u9002\u5408\u7ECF\u5E38\u67E5\u9605").addButton(
      (btn) => btn.setButtonText("\u6253\u5F00\u4FA7\u8FB9\u680F").onClick(() => {
        void this.plugin.activateCatalogView();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("\u6253\u5F00\u63D2\u4EF6\u4E00\u89C8\uFF08\u5F39\u7A97\uFF09").setDesc("\u5C45\u4E2D\u6D6E\u5C42\uFF0C\u4EC5\u5B98\u65B9\u8BF4\u660E\u53EA\u8BFB\u67E5\u9605\uFF0C\u8BBE\u7F6E\u6309\u94AE\u5728\u5361\u7247\u53F3\u4E0A\u89D2").addButton(
      (btn) => btn.setButtonText("\u6253\u5F00\u5F39\u7A97").onClick(() => {
        this.plugin.openCatalogModal();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("\u5237\u65B0\u5168\u90E8\u8BF4\u660E").setDesc(
      "\u4ECE Obsidian \u793E\u533A\u62C9\u53D6\u5B98\u65B9\u82F1\u6587\u8BF4\u660E\uFF0C\u5E76\u81EA\u52A8\u7FFB\u8BD1\u4E3A\u4E2D\u6587\uFF08\u5DF2\u624B\u52A8\u4FEE\u6539\u7684\u8BF4\u660E\u4E0D\u4F1A\u88AB\u8986\u76D6\uFF09"
    ).addButton(
      (btn) => btn.setButtonText("\u5F00\u59CB\u7FFB\u8BD1").onClick(async () => {
        btn.setDisabled(true);
        try {
          const n = await syncDescriptions(this.plugin);
          new import_obsidian3.Notice(`\u5DF2\u7FFB\u8BD1 ${n} \u6761\u63D2\u4EF6\u8BF4\u660E`);
        } finally {
          btn.setDisabled(false);
        }
      })
    );
    containerEl.createEl("p", {
      cls: "setting-item-description",
      text: "\u4FA7\u8FB9\u680F\uFF1A\u5B98\u65B9\u8BF4\u660E + \u53EF\u7F16\u8F91\u300C\u6211\u7684\u8BF4\u660E\u300D\u3002\u5F39\u7A97\uFF1A\u4EC5\u5B98\u65B9\u8BF4\u660E\u53EA\u8BFB\uFF0C\u8BBE\u7F6E\u6309\u94AE\u5728\u5361\u7247\u53F3\u4E0A\u89D2\u3002"
    });
  }
};

// src/types.ts
var DEFAULT_SETTINGS = {
  entries: {}
};

// src/main.ts
var PluginHelperPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(
      VIEW_TYPE_PLUGIN_CATALOG,
      (leaf) => new PluginCatalogView(leaf, this)
    );
    this.addRibbonIcon("book-open", "\u63D2\u4EF6\u8BF4\u660E\u4E66", () => {
      void this.activateCatalogView();
    });
    this.addCommand({
      id: "open-plugin-catalog-sidebar",
      name: "\u6253\u5F00\u63D2\u4EF6\u8BF4\u660E\u4E66\uFF08\u4FA7\u8FB9\u680F\uFF09",
      callback: () => void this.activateCatalogView()
    });
    this.addCommand({
      id: "open-plugin-catalog-modal",
      name: "\u6253\u5F00\u63D2\u4EF6\u8BF4\u660E\u4E66\uFF08\u5F39\u7A97\uFF09",
      callback: () => this.openCatalogModal()
    });
    this.addCommand({
      id: "refresh-plugin-descriptions",
      name: "\u5237\u65B0\u63D2\u4EF6\u8BF4\u660E\u7FFB\u8BD1",
      callback: async () => {
        new import_obsidian4.Notice("\u6B63\u5728\u7FFB\u8BD1\u63D2\u4EF6\u8BF4\u660E\u2026");
        try {
          const n = await syncDescriptions(this);
          new import_obsidian4.Notice(`\u5B8C\u6210\uFF1A\u66F4\u65B0\u4E86 ${n} \u6761\u8BF4\u660E`);
        } catch (e) {
          new import_obsidian4.Notice(`\u7FFB\u8BD1\u5931\u8D25\uFF1A${e}`);
        }
      }
    });
    this.addSettingTab(new PluginHelperSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      void this.maybeInitialSync();
    });
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  openCatalogModal() {
    new PluginCatalogModal(this.app, this).open();
  }
  async activateCatalogView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_PLUGIN_CATALOG);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (!leaf) return;
      await leaf.setViewState({
        type: VIEW_TYPE_PLUGIN_CATALOG,
        active: true
      });
    }
    await workspace.revealLeaf(leaf);
  }
  async maybeInitialSync() {
    const hasAny = Object.values(this.settings.entries).some(
      (e) => e.autoTranslatedDesc || e.customDesc
    );
    if (hasAny) return;
    try {
      await syncDescriptions(this);
    } catch (e) {
    }
  }
};
